# Generated by Django 5.2.2 on 2025-06-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleApi',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
